#!/bin/bash

# Forma de uso:
#
#         perfctr <CORE_ID> <GRUPO_PERFORMANCE> ./matmult <opcoe_matmult>
#
# Exemplo, para fazer as medições de performance de FLOPS_DP no core 3
#
#         perfctr 3 FLOPS_DP ./matmult 64
#

DATA_DIR=""

LIKWID_CMD="likwid-perfctr -C $1 -g $2 -m"
shift 2

echo "performance" > /sys/devices/system/cpu/cpufreq/policy${1}/scaling_governor

make purge matmult

METRICA="FLOPS_DP L2CACHE L3"
TEMPOS="${DATA_DIR}/Tempos.csv"
TAMANHOS="64 100 128 200 256 512 600 900 1024 2000"

for m in ${METRICA}
do
    LIKWID_LOG="${DATA_DIR}/${m}_${n}.log"

    for n in ${TAMANHOS}
    do

    done
done

${LIKWID_CMD} $*

echo "powersave" > /sys/devices/system/cpu/cpufreq/policy${1}/scaling_governor

# Para obter topologia dos cpu's
#      likwid-topology -c -g

# Para obter lista de grupos de indicadores de performance:
#      likwid-perfctr -a

# Para obter lista de Eventos e Contadores
#      likwid-perfctr -e

